services:
    marttiphpbb.calendarmono.repo:
        class: marttiphpbb\calendarmono\service\repo
        arguments:
            - '@dbal.conn'
            - '@content.visibility'
            - '@auth'
            - '@user'
            - '%tables.topics%'

    marttiphpbb.calendarmono.tag_listener:
        class: marttiphpbb\calendarmono\event\tag_listener
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmono.input_listener:
        class: marttiphpbb\calendarmono\event\input_listener
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmono.view_listener:
        class: marttiphpbb\calendarmono\event\view_listener
        arguments:
            - '@marttiphpbb.calendarmono.repo'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmono.calendarautoarchive_listener:
        class: marttiphpbb\calendarmono\event\calendarautoarchive_listener
        arguments:
            - '@marttiphpbb.calendarmono.repo'
        tags:
            - { name: event.listener }